package accesoHibernate;
// Generated 02-mar-2024 10:53:24 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empleados generated by hbm2java
 */
public class Empleados  implements java.io.Serializable {


     private Integer idEmpleado;
     private Incidencias incidencias;
     private String nombreUsuario;
     private String contrasena;
     private String nombreCompleto;
     private String telefonoContacto;
     private Set incidenciasesForIdEmpleadoDestino = new HashSet(0);
     private Set incidenciasesForIdEmpleadoOrigen = new HashSet(0);

    public Empleados() {
    }
    

    public Empleados(Incidencias incidencias, String nombreUsuario, String contrasena, String nombreCompleto, String telefonoContacto, Set incidenciasesForIdEmpleadoDestino, Set incidenciasesForIdEmpleadoOrigen) {
       this.incidencias = incidencias;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.nombreCompleto = nombreCompleto;
       this.telefonoContacto = telefonoContacto;
       this.incidenciasesForIdEmpleadoDestino = incidenciasesForIdEmpleadoDestino;
       this.incidenciasesForIdEmpleadoOrigen = incidenciasesForIdEmpleadoOrigen;
    }

    public Empleados(String nombreUsuario, String contrasena, String nombreCompleto, String telefonoContacto) {
        this.nombreUsuario = nombreUsuario;
        this.contrasena = contrasena;
        this.nombreCompleto = nombreCompleto;
        this.telefonoContacto = telefonoContacto;
    }

    public Empleados(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Incidencias getIncidencias() {
        return this.incidencias;
    }
    
    public void setIncidencias(Incidencias incidencias) {
        this.incidencias = incidencias;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    public String getNombreCompleto() {
        return this.nombreCompleto;
    }
    
    public void setNombreCompleto(String nombreCompleto) {
        this.nombreCompleto = nombreCompleto;
    }
    public String getTelefonoContacto() {
        return this.telefonoContacto;
    }
    
    public void setTelefonoContacto(String telefonoContacto) {
        this.telefonoContacto = telefonoContacto;
    }
    public Set getIncidenciasesForIdEmpleadoDestino() {
        return this.incidenciasesForIdEmpleadoDestino;
    }
    
    public void setIncidenciasesForIdEmpleadoDestino(Set incidenciasesForIdEmpleadoDestino) {
        this.incidenciasesForIdEmpleadoDestino = incidenciasesForIdEmpleadoDestino;
    }
    public Set getIncidenciasesForIdEmpleadoOrigen() {
        return this.incidenciasesForIdEmpleadoOrigen;
    }
    
    public void setIncidenciasesForIdEmpleadoOrigen(Set incidenciasesForIdEmpleadoOrigen) {
        this.incidenciasesForIdEmpleadoOrigen = incidenciasesForIdEmpleadoOrigen;
    }

    @Override
    public String toString() {
        return "Empleado: " + "Id: " + idEmpleado + ", Incidencias: " + incidencias +
                ", Usuario: " + nombreUsuario + ", Contrasena: " + contrasena +
                ", Nombre: " + nombreCompleto + ", Telefono: " + telefonoContacto +
                ", incidenciasesForIdEmpleadoDestino: " + incidenciasesForIdEmpleadoDestino +
                ", incidenciasesForIdEmpleadoOrigen: " + incidenciasesForIdEmpleadoOrigen;
    }




}


