package accesoHibernate;
// Generated 02-mar-2024 10:53:24 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Incidencias generated by hbm2java
 */
public class Incidencias  implements java.io.Serializable {


     private Integer idIncidencia;
     private Empleados empleadosByIdEmpleadoDestino;
     private Empleados empleadosByIdEmpleadoOrigen;
     private Date fechaHoraGeneracion;
     private String empleadoOrigen;
     private String empleadoDestino;
     private String detalleIncidencia;
     private Character tipoIncidencia;
     private Set empleadoses = new HashSet(0);

    public Incidencias() {
    }

    public Incidencias(Empleados empleadosByIdEmpleadoDestino, Empleados empleadosByIdEmpleadoOrigen, Date fechaHoraGeneracion, String empleadoOrigen, String empleadoDestino, String detalleIncidencia, Character tipoIncidencia, Set empleadoses) {
       this.empleadosByIdEmpleadoDestino = empleadosByIdEmpleadoDestino;
       this.empleadosByIdEmpleadoOrigen = empleadosByIdEmpleadoOrigen;
       this.fechaHoraGeneracion = fechaHoraGeneracion;
       this.empleadoOrigen = empleadoOrigen;
       this.empleadoDestino = empleadoDestino;
       this.detalleIncidencia = detalleIncidencia;
       this.tipoIncidencia = tipoIncidencia;
       this.empleadoses = empleadoses;
    }

    public Incidencias(Integer idIncidencia) {
        this.idIncidencia = idIncidencia;
    }

    public Incidencias(Date fechaHoraGeneracion, String empleadoOrigen, String empleadoDestino, String detalleIncidencia, Character tipoIncidencia) {
        this.fechaHoraGeneracion = fechaHoraGeneracion;
        this.empleadoOrigen = empleadoOrigen;
        this.empleadoDestino = empleadoDestino;
        this.detalleIncidencia = detalleIncidencia;
        this.tipoIncidencia = tipoIncidencia;
    }
    
   
    public Integer getIdIncidencia() {
        return this.idIncidencia;
    }
    
    public void setIdIncidencia(Integer idIncidencia) {
        this.idIncidencia = idIncidencia;
    }
    public Empleados getEmpleadosByIdEmpleadoDestino() {
        return this.empleadosByIdEmpleadoDestino;
    }
    
    public void setEmpleadosByIdEmpleadoDestino(Empleados empleadosByIdEmpleadoDestino) {
        this.empleadosByIdEmpleadoDestino = empleadosByIdEmpleadoDestino;
    }
    public Empleados getEmpleadosByIdEmpleadoOrigen() {
        return this.empleadosByIdEmpleadoOrigen;
    }
    
    public void setEmpleadosByIdEmpleadoOrigen(Empleados empleadosByIdEmpleadoOrigen) {
        this.empleadosByIdEmpleadoOrigen = empleadosByIdEmpleadoOrigen;
    }
    public Date getFechaHoraGeneracion() {
        return this.fechaHoraGeneracion;
    }
    
    public void setFechaHoraGeneracion(Date fechaHoraGeneracion) {
        this.fechaHoraGeneracion = fechaHoraGeneracion;
    }
    public String getEmpleadoOrigen() {
        return this.empleadoOrigen;
    }
    
    public void setEmpleadoOrigen(String empleadoOrigen) {
        this.empleadoOrigen = empleadoOrigen;
    }
    public String getEmpleadoDestino() {
        return this.empleadoDestino;
    }
    
    public void setEmpleadoDestino(String empleadoDestino) {
        this.empleadoDestino = empleadoDestino;
    }
    public String getDetalleIncidencia() {
        return this.detalleIncidencia;
    }
    
    public void setDetalleIncidencia(String detalleIncidencia) {
        this.detalleIncidencia = detalleIncidencia;
    }
    public Character getTipoIncidencia() {
        return this.tipoIncidencia;
    }
    
    public void setTipoIncidencia(Character tipoIncidencia) {
        this.tipoIncidencia = tipoIncidencia;
    }
    public Set getEmpleadoses() {
        return this.empleadoses;
    }
    
    public void setEmpleadoses(Set empleadoses) {
        this.empleadoses = empleadoses;
    }

    @Override
    public String toString() {
        return "Incidencias: " + "idIncidencia: " + idIncidencia + ", empleadosByIdEmpleadoDestino: " +
                empleadosByIdEmpleadoDestino + ", empleadosByIdEmpleadoOrigen:" + empleadosByIdEmpleadoOrigen +
                ", fechaHoraGeneracion: " + fechaHoraGeneracion + ", empleadoOrigen: " +
                empleadoOrigen + ", empleadoDestino: " + empleadoDestino + ", detalleIncidencia: " +
                detalleIncidencia + ", tipoIncidencia: " + tipoIncidencia + ", empleadoses: " + empleadoses;
    }




}


